#! /bin/sh
# /etc/init.d/aufzeichnung

### BEGIN INIT INFO
# Provides:          aufzeichnung
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Interactive:     true
# Short-Description: Klimaaufzeichnung
# Description:       Autostart der Aufzeichnung
### END INIT INFO


case "$1" in
	start)
		gpio mode 13 out # gelb
		gpio mode 12 out # rot
		gpio mode 3 out #grün
		echo "Warte 5 Sekunden"
		sleep 5
		if [ -f /home/pi/aufzeichnung.lock ]
		then
			echo "Die Aufzeichnung läuft bereits.\nWenn nicht, lösche aufzeichnung.lock im Home-Verzeichnis"
			exit 1
		fi
		if sudo python /home/pi/Temperaturmessung/Fremddateien/Adafruit_BMP085_auswertung.py |grep -q I2C 
		then 
			echo "Der Luftdruck-Sensor wurde nicht gefunden\nDas Programm wurde daher nicht gestartet"
			exit 1
		fi
		echo "Aufzeichnung wird gestartet"
		touch /home/pi/aufzeichnung.lock
		/home/pi/Temperaturmessung/export.sh > /dev/null 2>> /home/pi/log/aufzeichnung.txt &
		;;
	stop)
		echo "Aufzeichnung wird beendet"
		killall export.sh
		rm /home/pi/aufzeichnung.lock
		;;
	restart)
		echo "Aufzeichnung wird beendet"
		killall export.sh
		rm /home/pi/aufzeichnung.lock 
		if sudo python /home/pi/Temperaturmessung/Fremddateien/Adafruit_BMP085_auswertung.py |grep -q I2C 
		then 
			echo "Der Luftdruck-Sensor wurde nicht gefunden\nDas Programm wurde daher nicht gestartet"
			exit 1
		fi
		echo "Aufzeichnung wird gestartet"
		touch /home/pi/aufzeichnung.lock
		/home/pi/Temperaturmessung/export.sh > /dev/null 2>> /home/pi/log/aufzeichnung.txt &
		;;
	*)
		echo "Verwendung: /etc/init.d/aufzeichnung {start|stop}"
		exit 1
		;;
esac
exit 0


