#! /bin/sh
# /etc/init.d/aufzeichnung

case "$1" in
	start)
		if [ -f /home/pi/aufzeichnung.lock ]
		then
			echo "Die Aufzeichnung läuft bereits.\nWenn nicht, lösche aufzeichnung.lock im Home-Verzeichnis"
			exit 1
		fi
		echo "Aufzeichnung wird gestartet"
		touch /home/pi/aufzeichnung.lock
		/home/pi/Temperaturmessung/export.sh > /dev/null 2>> /home/pi/log/aufzeichnung.txt &
		;;
	stop)
		echo "Aufzeichnung wird beendet"
		killall export.sh
		rm /home/pi/aufzeichnung.lock
		;;
	*)
		echo "Verwendung: /etc/init.d/aufzeichnung {start|stop}"
		exit 1
		;;
esac
exit 0


