#! /bin/sh
# /etc/init.d/display

### BEGIN INIT INFO
# Provides:          display
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Interactive:     true
# Short-Description: Display
# Description:       Pythonskript, welches das Display steuert
### END INIT INFO

case "$1" in
	start)
		echo "Display wird gestartet"
		python /home/pi/Temperaturmessung/display.py > /home/pi/log/display 2>&1 &
		;;
	stop)
		echo "Display wird beendet"
		killall python
		;;
	*)
		echo "Verwendung: /etc/init.d/display {start|stop}"
		exit 1
		;;
esac
exit 0


